---

- hosts: all
  become: true
  tasks:


  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution_version == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu
    apt:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest   
    when: ansible_distribution =="Ubuntu"

  
